### ISSUE TITLE
Undefined reference to `reallocarray'

### ISSUE THREAD

**Issue by ehoffman2** [mkj/dropbear#429]
Was working with 2025.88.  Trying to compile 2026.90.

A call to reallocarray() was added in scp.c, which is not supported by older libc.

Our project is using libc 2.24, and I think that reallocarray() has been added in 2.26.

I see that this seems to be a reoccurring issue with different projects, and the way they worked around that is to provide a wrapper function in case libc does not support it.

Probably can be detected automatically in configure script (preferable option, as this make upgrading version seamless), or as a manual option provided to configure, ex: `--with-libc-compat`.

**Comment by mkj** [comment]
This should already be fixed in #427
