### ISSUE TITLE
static_assert prevents build on ancient compilers (gcc < 4.6)

### ISSUE THREAD

**Issue by andreas-wehrmann** [mkj/dropbear#359]
Unfortunately, I have to support a rather old embedded Linux board and in order to keep it as secure as I can
I update libraries and services regularly; this includes Dropbear SSH.
When I wanted to update from 2024.86 to 2025.87 I noticed a linker failure because the new module mlkem768.c
makes use of `static_assert` which my GCC version (4.5.98) doesn't know and a toolchain update is out of the question... and not even available.

Compiling the TU gives this output:
```
gcc -std=gnu99 -D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fPIE -Wundef -fno-strict-overflow -Wno-pointer-sign -O2 -W -Wall -Wno-pointer-sign  -I./src/../libtomcrypt/src/headers/ -I. -I./src -DDROPBEAR_SERVER -DDROPBEAR_CLIENT -DPROGRESS_METER -DDBMULTI_dropbear -DDBMULTI_dbclient -DDBMULTI_dropbearkey -DDBMULTI_dropbearconvert -DDBMULTI_scp -DDROPBEAR_MULTI src/mlkem768.c -o obj/mlkem768.o -c
src/mlkem768.c:49:9: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
src/mlkem768.c:52:9: warning: expected [error|warning|ignored] after '#pragma GCC diagnostic'
src/mlkem768.c: In function 'crypto_kem_mlkem768_keypair':
src/mlkem768.c:63:2: warning: implicit declaration of function 'static_assert'
```

And when linking the multibin it throws:
```
./obj/mlkem768.o: In function `crypto_kem_mlkem768_keypair':
mlkem768.c:(.text+0xf08c): undefined reference to `static_assert'
mlkem768.c:(.text+0xf096): undefined reference to `static_assert'
./obj/mlkem768.o: In function `crypto_kem_mlkem768_enc':
mlkem768.c:(.text+0xfe36): undefined reference to `static_assert'
mlkem768.c:(.text+0xfe40): undefined reference to `static_assert'
mlkem768.c:(.text+0xfe4a): undefined reference to `static_assert'
./obj/mlkem768.o:mlkem768.c:(.text+0x1022a): more undefined references to `static_assert' follow
```

If you say you don't want to support these ancient platforms, I can understand.
I'd be fine with just disabling this module (or just patch the source to throw the static_asserts out).

I couldn't find any uses of `static_assert` outside of `src/mlkem768.c`
so maybe there could be an availability check during configure and only use static_assert if the compiler supports it?

**Comment by andreas-wehrmann** [comment]
Sorry for the noise; I've just noticed that this has already been resolved in current master.
